default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: nps_development
  encoding: unicode

test:
  <<: *default
  database: nps_test
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres


production:
  <<: *default
  database: nps_production
  encoding: unicode

